### ISSUE TITLE
Sections introduce a new scope

### ISSUE THREAD

**Issue by guydunton** [guydunton/rust-catch#24]
Since section introduce a new scope this means that you cannot put code after a section relying on any variables within that section. This prevents common code being put after a section e.g.
```rust
test("My test") {
    section("test for one thing") {
         let result = myFunction();
    }
    section("test for a second thing") {
         let result = myFunction(withParam);
    }
    assert_eq!(result, passed);
}
```

**Comment by PTaylor-us** [comment]
I do believe this is also an issue in Catch2 normally worked around by creating a function that contains the common code and calling it in each section. If you have more sections after the `assert_eq!(result, passed);` that would cause a problem as the first two sections aren't even executed when the additional sections are.

**Comment by guydunton** [comment]
@PTaylor-us Thanks for pointing out that Catch2 has the same issue. 

The more I think about it the more I think that fixing this example isn't something that would make the library better. I've been using it for my own projects and haven't really found this to be a widespread issue.
